obenimdeoyuncagimvc/Controllers/emanetverController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using obenimdeoyuncagimvc.Models.Entity;
using obenimdeoyuncagimvc.Controllers;

namespace obenimdeoyuncagimvc.Controllers
{
    public class emanetverController : Controller
    {
        // GET: emanetver
        mvc_oyuncakEntities db = new mvc_oyuncakEntities();
        public ActionResult Index()
        {
            var emanetler = db.emanetoyuncaklar.ToList();
            return View(emanetler);
        }
        //public actionresult emanetver(string barkodno)
        //{

        //    var sepetdbınstance = db.sepet.where(b => b.barkodno == barkodno).firstordefault();


        //    emanetoyuncaklar x = new emanetoyuncaklar();
        //    x.tc = emanetoyuncaklardbınstance.tc;
        //    x.adsoyad = emanetoyuncaklardbınstance.adsoyad;
        //    x.yas = emanetoyuncaklardbınstance.yas;
        //    x.barkodno = emanetoyuncaklardbınstance.barkodno;
        //    x.oyuncakadi = emanetoyuncaklardbınstance.oyuncakadi;
        //    x.ureticifirma = emanetoyuncaklardbınstance.ureticifirma;
        //    x.oyuncakboyutu = emanetoyuncaklardbınstance.oyuncakboyutu;
        //    x.oyuncakyasgrubu = emanetoyuncaklardbınstance.oyuncakyasgrubu;
        //    x.oyuncaksayisi = emanetoyuncaklardbınstance.oyuncaksayisi;

        //    x.teslimtarihi = "28.11.2022";
        //    x.iadetarihi = "28.11.2022";

        //    db.emanetoyuncaklar.add(x);
        //    db.savechanges();
        //    return view("ındex");
        //}
        [HttpPost]
        public ActionResult sil(string tc)
        {
            var emanetoyuncaklar = db.emanetoyuncaklar.Find(tc);
            db.emanetoyuncaklar.Remove(emanetoyuncaklar);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

obenimdeoyuncagimvc/Views/emanetver/Index.cshtml
@using obenimdeoyuncagimvc.Models.Entity
@model List<emanetoyuncaklar>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_mainLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>tc</th>
        <th>adsoyad</th>
        <th>yas</th>
        <th>telefon</th>
        <th>barkodno</th>
        <th>oyuncakadi</th>
        <th>ureticifirma</th>
        <th>oyuncakboyutu</th>
        <th>oyuncakyasgrubu</th>
        <th>oyuncaksayisi</th>
        <th>teslimtarihi</th>
        <th>iadetarihi</th>
        <th>iade et</th>

    </tr>
    <tbody>
        @foreach (var emanetoyuncaklar in Model)
        {
            using (Html.BeginForm("sil", "emanetver", new { tc = emanetoyuncaklar.tc }))
            {
                <tr>
                    <td>@emanetoyuncaklar.tc</td>
                    <td>@emanetoyuncaklar.adsoyad</td>
                    <td>@emanetoyuncaklar.yas</td>
                    <td>@emanetoyuncaklar.telefon</td>
                    <td>@emanetoyuncaklar.barkodno</td>
                    <td>@emanetoyuncaklar.oyuncakadi</td>
                    <td>@emanetoyuncaklar.ureticifirma</td>
                    <td>@emanetoyuncaklar.oyuncakboyutu</td>
                    <td>@emanetoyuncaklar.oyuncakyasgrubu</td>
                    <td>@emanetoyuncaklar.oyuncaksayisi</td>
                    <td>@emanetoyuncaklar.teslimtarihi</td>
                    <td>@emanetoyuncaklar.iadetarihi</td>
                    <td><input type="submit" value="sil" class="btn btn-danger" /></td>

                </tr>
            }
        }
    </tbody>
</table>