obenimdeoyuncagimvc/Models/Entity/sepet.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obenimdeoyuncagimvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class sepet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sepet()
        {
            this.emanetoyuncaklar = new HashSet<emanetoyuncaklar>();
        }
    
        public string barkodno { get; set; }
        public string oyuncakadi { get; set; }
        public string ureticifirma { get; set; }
        public string oyuncakboyutu { get; set; }
        public string oyuncakyasgrubu { get; set; }
        public int oyuncaksayisi { get; set; }
        public string teslimtarihi { get; set; }
        public string iadetarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emanetoyuncaklar> emanetoyuncaklar { get; set; }
        public virtual oyuncak oyuncak { get; set; }
    }
}

obenimdeoyuncagimvc/Controllers/sepetController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using obenimdeoyuncagimvc.Models.Entity;

namespace obenimdeoyuncagimvc.Controllers
{
    public class sepetController : Controller
    {
        // GET: uye

        mvc_oyuncakEntities db = new mvc_oyuncakEntities();
        [HttpGet]
        public ActionResult Index()
        {
            var degerler = db.sepet.ToList();
            return View(degerler);

        }
        
        //[Route("/sepet/SepeteEkle/{barkodno}")]
        public ActionResult SepeteEkle(String barkodno)
        {

            var sepetDbInstance =  db.oyuncak.Find(barkodno);

            sepet x = new sepet();
            x.barkodno = sepetDbInstance.barkodno;
            x.oyuncakadi = sepetDbInstance.oyuncakadi;
            x.ureticifirma = sepetDbInstance.ureticifirma;
            x.oyuncakboyutu = sepetDbInstance.oyuncakboyutu;
            x.oyuncakyasgrubu = sepetDbInstance.oyuncakyasgrubu;
            x.teslimtarihi = "28.11.2022";
            x.iadetarihi = "28.11.2022";

            db.sepet.Add(x);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult temizle(string barkodno)
        {
            var sepet = db.sepet.Find(barkodno);
            db.sepet.Remove(sepet);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult uyebilgiekle(FormCollection form)
        {
            System.Diagnostics.Debug.WriteLine(form["barkodno"]+"1215156156");
            var DbInstanceuye = db.uye.Find(form["tc"]);
           
            var DbIntancesepet = db.sepet.Find(form["barkodno"]);
            uye x = new uye();
            sepet y = new sepet();  
            x.tc = DbInstanceuye.tc;
            x.adsoyad = DbInstanceuye.adsoyad;
            x.yas= DbInstanceuye.cinsiyet;
            x.cinsiyet = DbInstanceuye.cinsiyet;
            x.telefon = DbInstanceuye.telefon;
            y.barkodno = form["barkodno"];
            y.oyuncakadi = DbIntancesepet.oyuncakadi;

            y.ureticifirma = DbIntancesepet.ureticifirma;
            y.oyuncakboyutu = DbIntancesepet.oyuncakboyutu;
            y.oyuncakyasgrubu = DbIntancesepet.oyuncakyasgrubu;
            y.oyuncaksayisi = DbIntancesepet.oyuncaksayisi;
            y.teslimtarihi = "28.11.2022";
            y.iadetarihi = "28.11.2022";
            emanetoyuncaklar eo = new emanetoyuncaklar();
            eo.tc = x.tc;
            eo.adsoyad = x.adsoyad;
            eo.yas = x.yas;
            eo.telefon = x.telefon;
            eo.barkodno = form["barkodno"];
            eo.oyuncakadi = y.oyuncakadi;
            eo.ureticifirma = y.ureticifirma;
            eo.oyuncakboyutu = y.oyuncakboyutu;
            eo.oyuncakyasgrubu = y.oyuncakyasgrubu;
            eo.oyuncaksayisi = y.oyuncaksayisi;
            eo.teslimtarihi = y.teslimtarihi;
            eo.iadetarihi = y.iadetarihi;

            db.emanetoyuncaklar.Add(eo);
           
            db.SaveChanges();
            return RedirectToAction("Index");



        }
    }
}

obenimdeoyuncagimvc/Views/sepet/Index.cshtml
@using obenimdeoyuncagimvc.Models.Entity
@model List<sepet>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_mainLayout.cshtml";
}

<script>
    function myFunction() {
        
        $("#Modal1").modal();
    }
</script>
       


<table class="table table-bordered">
    <tr>
        <th>Barkod No</th>
        <th> Oyuncak Adı</th>
        <th> Üretici Firma</th>
        <th> Oyuncak Boyutu</th>
        <th> Oyuncak Yaş Grubu</th>
        <th> Oyuncak Sayısı</th>
        <th>Teslim Tarihi</th>
        <th> İade Tarihi</th>
        <th> Temizle</th>
        <th> Güncelle</th>
        <th>Emanet ver</th>

    </tr>
    <tbody>
        @foreach (var sepet in Model)
        {
            using (Html.BeginForm("temizle", "sepet", new { barkodno = sepet.barkodno }))
            {
                <input type="hidden" value="@sepet.barkodno" name="barkodno1" id="barkodno1" />
                <tr>
                    <th>@sepet.barkodno</th>

                    <th>@sepet.oyuncakadi</th>
                    <th>@sepet.ureticifirma</th>
                    <th>@sepet.oyuncakboyutu</th>
                    <th>@sepet.oyuncakyasgrubu</th>
                    <th>@sepet.oyuncaksayisi</th>
                    <th>@sepet.teslimtarihi</th>
                    <th>@sepet.iadetarihi</th>
                    <td><input type="submit" value="temizle" class="btn btn-danger" /></td>
                    <!--<td><a href="/uye/sil/@sepet.barkodno" class="btn btn-danger">çıkart</a></td>-->
                    <td><a href="/uye/güncelle/@sepet.barkodno" class="btn btn-success">güncelle</a></td>
                    <td><button type="button" class="btn btn-primary" onclick="myFunction()" data-toggle="modal">Emanet ver</button></td>

                </tr>
            }
        }
</table>

<div class="modal" id="Modal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">Emanet Verme Ekranı</h2>
            </div>
            @using (Html.BeginForm("uyebilgiekle", "sepet", FormMethod.Post))
            {
                <div class="modal-body">
                    <label>
                        Emanet Verilecek Kişinin T.C Numarası:
                    </label>
                    <input type="text" name="tc" class="form-control" />
                    <label>
                        Emanet Verilecek Kişinin Adı Soyadı:
                    </label>
                    <input type="text" name="adsoyad" class="form-control" />
                    <input type="hidden" id="barkodno1" />
                    <input type="submit" value="Kaydet" />
                </div>
            }
        </div>
    </div>
</div>