obenimdeoyuncagimvc/Models/Entity/oyuncak.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obenimdeoyuncagimvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class oyuncak
    {
        public string barkodno { get; set; }
        public string oyuncakadi { get; set; }
        public string oyuncakboyutu { get; set; }
        public string oyuncakyasgrubu { get; set; }
        public string ureticifirma { get; set; }
        public string oyuncakturu { get; set; }
        public int stoksayisi { get; set; }
        public string rafno { get; set; }
        public string açıklama { get; set; }
        public string kayıttarihi { get; set; }
    
        public virtual sepet sepet { get; set; }
    }
}

obenimdeoyuncagimvc/Controllers/oyuncakController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlTypes;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using obenimdeoyuncagimvc.Models.Entity;


namespace obenimdeoyuncagimvc.Controllers
{
    public class oyuncakController : Controller
    {
        // GET: oyuncak
        mvc_oyuncakEntities db = new mvc_oyuncakEntities();
        public ActionResult Index()
        {
            var degerler = db.oyuncak.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult yenioyuncak()
        {
            
            return View();
        }
        [HttpPost]
        public ActionResult yenioyuncak(oyuncak p1)
        {

            var count = db.oyuncak.Count(u => u.barkodno == p1.barkodno);
            if (count > 0)
            {
                return Content("<script language='javascript' type='text/javascript'>alert('Böyle bir Kayıt var.');</script>");

            }
            else
            {
                db.oyuncak.Add(p1);
                db.SaveChanges();
            }

            return RedirectToAction("Index");


        }
        [HttpPost]
        public ActionResult sil(string barkodno)
        {
            var oyuncak = db.oyuncak.Find(barkodno);
            db.oyuncak.Remove(oyuncak);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    /*    public ActionResult emanetver(string barkodno)
        {
            var oyuncak = db.emanetoyuncaklar.Add(barkodno);

            //db.oyuncak.Remove(oyuncak);baro
           // db.SaveChanges();
            return RedirectToAction("Index");
        }*/

        public ActionResult oyuncakgetir(string barkodno)
        {
            var oyuncak = db.oyuncak.Find(barkodno);
            return View("oyuncakgetir", oyuncak);
        }
        public ActionResult guncelle(oyuncak p1)
        {
            var oyuncak = db.oyuncak.Find(p1.barkodno);
            oyuncak.barkodno = p1.barkodno;
            oyuncak.oyuncakadi = p1.oyuncakadi;
            oyuncak.oyuncakboyutu = p1.oyuncakboyutu;
            oyuncak.oyuncakyasgrubu = p1.oyuncakyasgrubu;
            oyuncak.ureticifirma = p1.ureticifirma;
            oyuncak.oyuncakturu = p1.oyuncakturu;
            oyuncak.stoksayisi = p1.stoksayisi;
            oyuncak.rafno =p1.rafno;
            oyuncak.kayıttarihi=p1.kayıttarihi;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }

}

obenimdeoyuncagimvc/Views/oyuncak/Index.cshtml
@using obenimdeoyuncagimvc.Models.Entity
@model List<oyuncak>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_mainLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>Barkod No</th>
        <th> Oyuncak Adı</th>
        <th> Oyuncak Boyutu</th>
        <th> Oyuncak Yaş Grubu</th>
        <th> Üretici Firma</th>
        <th> Oyuncak Türü</th>
        <th> Stok Sayısı</th>
        <th> Raf Numarası</th>
        <th> Açıklama </th>
        <th> Kayıt Tarihi</th>
        <th> Sil</th>
        <th> Güncelle</th>
        <th> Sepete Ekle</th>

    </tr>
    <tbody>
        @foreach (var oyuncak in Model)
        {

            using (Html.BeginForm("sil", "oyuncak", new { barkodno = oyuncak.barkodno }))
            {
                <tr>
                    <th>@oyuncak.barkodno</th>
                    <th>@oyuncak.oyuncakadi</th>
                    <th>@oyuncak.oyuncakboyutu</th>
                    <th>@oyuncak.oyuncakyasgrubu</th>
                    <th>@oyuncak.ureticifirma</th>
                    <th>@oyuncak.oyuncakturu</th>
                    <th>@oyuncak.stoksayisi</th>
                    <th>@oyuncak.rafno</th>
                    <th>@oyuncak.açıklama</th>
                    <th>@oyuncak.kayıttarihi</th>
                    <td><input type="submit" value="sil" class="btn btn-danger" /></td>
                    <td><input type="submit" value="guncelle" class="btn btn-warning" /></td>
                    <td><a href="/sepet/SepeteEkle?barkodno=@oyuncak.barkodno" class="btn btn-primary">sepete ekle</a></td>
                </tr>
}

        }
    </tbody>
</table>

<a href="/oyuncak/yenioyuncak/" class="btn btn-primary">Yeni Oyuncak Ekle</a>

obenimdeoyuncagimvc/Views/oyuncak/oyuncakgetir.cshtml
@model  obenimdeoyuncagimvc.Models.Entity.oyuncak
@{
    ViewBag.Title = "oyuncakgetir";
    Layout = "~/Views/Shared/_mainLayout.cshtml";
}

@using (Html.BeginForm("Guncelle", "oyuncak", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.barkodno)
        @Html.TextBoxFor(m => m.barkodno, new { @class = "form-control" })
        <br />
        @Html.LabelFor(m => m.oyuncakadi)
        @Html.TextBoxFor(m => m.oyuncakadi, new { @class = "form-control" })

        @Html.LabelFor(m => m.oyuncakboyutu)
        @Html.TextBoxFor(m => m.oyuncakboyutu, new { @class = "form-control" })

        @Html.LabelFor(m => m.oyuncakyasgrubu)
        @Html.TextBoxFor(m => m.oyuncakyasgrubu, new { @class = "form-control" })

        @Html.LabelFor(m => m.ureticifirma)
        @Html.TextBoxFor(m => m.ureticifirma, new { @class = "form-control" })

        @Html.LabelFor(m => m.oyuncakturu)
        @Html.TextBoxFor(m => m.oyuncakturu, new { @class = "form-control" })

        @Html.LabelFor(m => m.stoksayisi)
        @Html.TextBoxFor(m => m.stoksayisi, new { @class = "form-control" })

        @Html.LabelFor(m => m.rafno)
        @Html.TextBoxFor(m => m.rafno, new { @class = "form-control" })

        @Html.LabelFor(m => m.açıklama)
        @Html.TextBoxFor(m => m.açıklama, new { @class = "form-control" })

        @Html.LabelFor(m=>m.kayıttarihi)
        @Html.TextBoxFor(m => m.kayıttarihi, new { @class = "form-control" })


    </div>
    <div>
        <button class="btn btn-warning">Oyuncak Güncelle</button>
    </div>
}

obenimdeoyuncagimvc/Views/oyuncak/yenioyuncak.cshtml
@model obenimdeoyuncagimvc.Models.Entity.oyuncak
@{
    ViewBag.Title = "yenioyuncak";
    Layout = "~/Views/Shared/_mainLayout.cshtml";
}
<script type="text/javascript">
function SayiGirme(degisken) {
degisken = (degisken) ? degisken : window.event;
var charCode = (degisken.which) ? degisken.which : degisken.keyCode;
if (charCode > 31 && (charCode < 48 || charCode > 57)) {
return false;
}
return true;
    }


</script>

<script type="text/javascript">
    function HarfGirme(degisken) {
        degisken = (degisken) ? degisken : window.event;
        var charCode = (degisken.which) ? degisken.which : degisken.keyCode;
        if ((charCode >= 65 && charCode <= 90) || (charCode >= 97 && charCode <= 122)) {
            return true;
        }
        return false;
    }

</script>


<form class="form-group" method="post">
    <div>
        <label>Oyuncak Barkod No</label>
        <input type="text" class="form-control" name="barkodno"  runat="server"  onkeypress="return SayiGirme(event)" />,
    </div>
    <div>
        <label>Oyuncak Adı</label>
        <input type="text" class="form-control" name="oyuncakadi" runat="server" onkeypress="return HarfGirme(event)"  />
    </div>
    <div>
        <label>Oyuncak Boyutu</label>
        <input type="text" class="form-control" name="oyuncakboyutu" />
    </div>
    <div>
        <label>Oyuncak Yaş Grubu</label>
        <input type="text" class="form-control" name="oyuncakyasgrubu" />
    </div>
    <div>
        <label>Üretici Firma</label>
        <input type="text" class="form-control" name="ureticifirma" runat="server" onkeypress="return HarfGirme(event)" />
    </div>
    <div>
        <label>Oyuncak Türü</label>
        <input type="text" class="form-control" name="oyuncakturu" />
    </div>
    <div>
        <label>Oyuncak Stok Sayısı</label>
        <input type="number" class="form-control" name="stoksayisi" />
    </div>
    <div>
        <label>Oyuncak Raf Numarası</label>
        <input type="text" class="form-control" name="rafno" runat="server"  onkeypress="return SayiGirme(event)"  />
    </div>
    <div>
        <label>Açıklama</label>
        <input type="text" class="form-control" name="açıklama" />
    </div>
    <div>
        <label>Kayıt Tarihi</label>
        <input type="date" class="form-control" name="kayıttarihi" />
    </div>


    <div style="margin-top:15px">
        <button class="btn btn-info">Oyuncak Ekle</button>
    </div>
</form>