obenimdeoyuncagimvc/Controllers/uyeeController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using obenimdeoyuncagimvc.Models.Entity;
using System.Net.Mail;

namespace obenimdeoyuncagimvc.Controllers
{
    public class uyeeController : Controller
    {
        // GET: uye
        mvc_oyuncakEntities db = new mvc_oyuncakEntities();
        public ActionResult Index()
        {
            var degerler = db.uye.ToList();   
            return View(degerler);
        }
        [HttpGet]
        public ActionResult yeniuye()
        {
            return View();
        }
        [HttpPost]
        public ActionResult yeniuye(uye p1)
        {
            var count = db.uye.Count(u => u.tc == p1.tc);
            if (count > 0)
            {
                return Content("<script language='javascript' type='text/javascript'>alert('Böyle bir Kayıt var.');</script>");

            }
            else
            {
                db.uye.Add(p1);
                db.SaveChanges();
            }
            
            return RedirectToAction("Index");




        }
        [HttpPost]
        public ActionResult sil(string tc)
        {
            var uye = db.uye.Find(tc);
            
            db.uye.Remove(uye);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
       
    }
}

obenimdeoyuncagimvc/Views/uyee/Index.cshtml
@using obenimdeoyuncagimvc.Models.Entity
@model List<uye>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_mainLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th> Üye TC'si:</th>
        <th> Üye Ad-Soyad:</th>
        <th> Üye Yaş:</th>
        <th> Cinsiyet:</th>
        <th> Üye Telefon:</th>
        <th> Üye Adres:</th>
        <th> Üye E-mail:</th>
        <th> Oyuncak Sayısı:</th>
        <th> Sil</th>
        <th> Güncelle</th>

    </tr>
    <tbody>
        @foreach(var uye in Model)
        {
            using (Html.BeginForm("sil", "uyee", new { tc = uye.tc }))
            {
        <tr>
            <th>@uye.tc</th>
            <th>@uye.adsoyad</th>
            <th>@uye.yas</th>
            <th>@uye.cinsiyet</th>
            <th>@uye.telefon</th>
            <th>@uye.adres</th>
            <th>@uye.email</th>
            <th>@uye.oyuncaksayisi</th>
            <!--<td><a href="/uyee/sil/@uye.tc" class="btn btn-danger">sil</a></td>-->
            <td>
            <input type="submit" value="sil" class="btn btn-danger" /></td>
            <td><a href="/uyee/güncelle/@uye.tc" class="btn btn-warning">güncelle</a></td>
            

        </tr>
            }
        }
    </tbody>
        
</table>
<a href="/uyee/yeniuye/" class="btn btn-primary">Yeni Üye Ekle</a>

obenimdeoyuncagimvc/Views/uyee/yeniuye.cshtml
@{
    ViewBag.Title = "yeniuye";
    Layout = "~/Views/Shared/_mainLayout.cshtml";
}
<script type="text/javascript">
function SayiGirme(degisken) {
degisken = (degisken) ? degisken : window.event;
var charCode = (degisken.which) ? degisken.which : degisken.keyCode;
if (charCode > 31 && (charCode < 48 || charCode > 57)) {
return false;
}
return true;
    }
    

</script>
  
   
<script type="text/javascript">
        function HarfGirme(degisken) {
            degisken = (degisken) ? degisken : window.event;
            var charCode = (degisken.which) ? degisken.which : degisken.keyCode;
            if ((charCode >= 65 && charCode <= 90) || (charCode >= 97 && charCode <= 122)) {
                return true;
            }
            return false;
        }

</script>

<form method="post" class="form-group">
    <div>
        <label>
            <label>Üye TC</label>
            <input type="text" minlength="11" maxlength="11" class="form-control" name="tc"  runat="server"  onkeypress="return SayiGirme(event)">
            <label>Ad Soyad</label>
            <input type="text" class="form-control" name="adsoyad" runat="server" onkeypress="return HarfGirme(event)" />
            <label>Yaş</label>
            <input type="text" class="form-control" name="yas"  runat="server"  onkeypress="return SayiGirme(event)"/>
            <label>Cinsiyet</label>
            <input type="text" class="form-control" name="cinsiyet" runat="server" onkeypress="return HarfGirme(event)" />
            <label>Telefon Numarası</label>
            <input type="text" minlength="11" maxlength="11" class="form-control" name="telefon"  runat="server"  onkeypress="return SayiGirme(event)" />
            <label>Adres</label>
            <input type="text" class="form-control" name="adres" />
            <label>E-mail</label>
            <input type="email" class="form-control" name="email" />
            <label>Oyuncak Sayısı</label>
            <input type="number" class="form-control" name="oyuncaksayisi" />
        </label>
    </div>
    <div>
        <button class="btn btn-info">Üye Ekle</button>
    </div>
</form>